# anchors
.altherma_base: &altherma_base
  platform: altherma_hub
  altherma_hub_id: altherma_hub_1

.temp: &temp
  <<: *altherma_base
  device_class: temperature
  unit_of_measurement: °C
  state_class: measurement
  accuracy_decimals: 1

.binary: &binary
  <<: *altherma_base

.current: &current
  <<: *altherma_base
  device_class: current
  unit_of_measurement: A
  icon: mdi:current-ac
  state_class: measurement
  accuracy_decimals: 1  

.pressure_bar: &pressure_bar
  <<: *altherma_base
  device_class: pressure
  unit_of_measurement: bar
  state_class: measurement
  accuracy_decimals: 1

.rps: &rps
  <<: *altherma_base
  unit_of_measurement: rps
  state_class: measurement

.text: &text
  <<: *altherma_base


sensor:
  # --- Outdoor Unit Temps ---
  - <<: *temp
    name: Outdoor air temp. (R1T)
    register: 0x20
    offset: 0
    convid: 105
    datasize: 2

  - <<: *temp
    name: O⁄U Heat Exch. Temp. (R4T)
    register: 0x20
    offset: 2
    convid: 105
    datasize: 2
    entity_category: diagnostic

  - <<: *temp
    name: Discharge pipe temp. (R2T)
    register: 0x20
    offset: 4
    convid: 105
    datasize: 2
    entity_category: diagnostic

  - <<: *temp
    name: Suction pipe temp. (R3T)
    register: 0x20
    offset: 6
    convid: 105
    datasize: 2
    entity_category: diagnostic

  - <<: *temp
    name: Heat exchanger mid-temp. (R5T)
    register: 0x20
    offset: 8
    convid: 105
    datasize: 2
    entity_category: diagnostic

  - <<: *temp
    name: Liquid pipe temp. (R6T)
    register: 0x20
    offset: 10
    convid: 105
    datasize: 2
    entity_category: diagnostic

  # --- Pressures ---
  - <<: *pressure_bar
    name: High Pressure
    register: 0x20
    offset: 12
    convid: 105
    datasize: 2

  - <<: *pressure_bar
    name: Low Pressure
    register: 0x20
    offset: 14
    convid: 105
    datasize: 2

  # --- Currents ---
  - <<: *current
    name: INV primary current
    register: 0x21
    offset: 0
    convid: 105
    datasize: 2

  - <<: *current
    name: INV secondary current
    register: 0x21
    offset: 2
    convid: 105
    datasize: 2

  # --- Additional temps ---
  - <<: *temp
    name: INV fin temp.
    register: 0x21
    offset: 4
    convid: 105
    datasize: 2

  - <<: *temp
    name: Brine inlet temp.
    register: 0x21
    offset: 6
    convid: 105
    datasize: 2

  - <<: *temp
    name: Brine outlet temp.
    register: 0x21
    offset: 8
    convid: 105
    datasize: 2

  - <<: *temp
    name: Compressor outlet temperature
    register: 0x21
    offset: 10
    convid: 105
    datasize: 2

  - <<: *temp
    name: Refrig. temp. evap. Out
    register: 0x21
    offset: 12
    convid: 105
    datasize: 2

  # --- Frequency ⁄ Fan ---
  - <<: *rps
    name: INV frequency (rps)
    register: 0x30
    offset: 0
    convid: 152
    datasize: 1

  - <<: *altherma_base
    name: Fan 1 (step)
    register: 0x30
    offset: 1
    convid: 211
    datasize: 1

  - <<: *altherma_base
    name: Fan 2 (step)
    register: 0x30
    offset: 2
    convid: 211
    datasize: 1

  # --- Water side ---
  - <<: *temp
    name: Inlet water temp. (DMW)
    register: 0x30
    offset: 10
    convid: 112
    datasize: 1

  - <<: *temp
    name: Outlet water heat exchanger temp (DLWB2)
    register: 0x30
    offset: 11
    convid: 112
    datasize: 1

  # --- Indoor water temps ---
  - <<: *temp
    name: Leaving water temp. before BUH (R1T)
    register: 0x61
    offset: 2
    convid: 105
    datasize: 2

  - <<: *temp
    name: Leaving water temp. after BUH (R2T)
    register: 0x61
    offset: 4
    convid: 105
    datasize: 2

  - <<: *temp
    name: Inlet water temp. (R4T)
    register: 0x61
    offset: 8
    convid: 105
    datasize: 2

  - <<: *temp
    name: DHW tank temp. (R5T)
    register: 0x61
    offset: 10
    convid: 105
    datasize: 2

  # --- Flow ⁄ Pressure ---
  - <<: *altherma_base
    name: Flow sensor (l⁄min)
    register: 0x62
    offset: 9
    convid: 105
    datasize: 2
    unit_of_measurement: l⁄min
    state_class: measurement
    accuracy_decimals: 1

  - <<: *pressure_bar
    name: Water pressure
    register: 0x62
    offset: 11
    convid: 105
    datasize: 1

  - <<: *altherma_base
    name: Water pump signal (0:max-100:stop)
    register: 0x62
    offset: 12
    convid: 152
    datasize: 1
    accuracy_decimals: 0


binary_sensor:
  - <<: *binary
    name: Thermostat ON⁄OFF
    device_class: running
    register: 0x60
    offset: 2
    convid: 303
    datasize: 1

  - <<: *binary
    name: Defrost Operation
    register: 0x10
    offset: 1
    convid: 304
    datasize: 1

  - <<: *binary
    name: Freeze Protection
    device_class: cold
    register: 0x60
    offset: 2
    convid: 302
    datasize: 1

  - <<: *binary
    name: Silent Mode
    device_class: sound
    register: 0x60
    offset: 2
    convid: 301
    datasize: 1

  - <<: *binary
    name: 3way valve (DHW⁄Space)
    register: 0x60
    offset: 12
    convid: 306
    datasize: 1

  - <<: *binary
    name: BUH Step1
    register: 0x60
    offset: 12
    convid: 304
    datasize: 1

  - <<: *binary
    name: BUH Step2
    register: 0x60
    offset: 12
    convid: 303
    datasize: 1

  - <<: *binary
    name: PHE Heater
    register: 0x62
    offset: 8
    convid: 304
    datasize: 1


text_sensor:
  - <<: *text
    name: I⁄U operation mode
    icon: mdi:state-machine
    register: 0x60
    offset: 2
    convid: 315
    datasize: 1

  - <<: *text
    name: Error Code
    register: 0x60
    offset: 3
    convid: 204
    datasize: 1

  - <<: *text
    name: Error detailed code
    register: 0x60
    offset: 4
    convid: 152
    datasize: 1

  - <<: *text
    name: Error type
    register: 0x60
    offset: 5
    convid: 203
    datasize: 1
