esphome:
  name: esphome-altherma
  friendly_name: ESPHome Altherma
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  # Uncomment below for using mock uart during development:
  #platformio_options:
  #  build_flags:
  #    - -DUSE_MOCK_UART

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome

wifi:
  # Set up a wifi access point using the device name above
  ap:

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  data_bits: 8
  parity: EVEN
  stop_bits: 1

external_components:
# Uncomment below if you want to "Take Control" in ESPHome Device Builder
#   - source: github://jjohnsen/esphome-altherma@main
#     components: [altherma_hub]
# Comment below if you want to "Take Control" in ESPHome Device Builder
  - source:
      type: local
      path: components

altherma_hub:
  id: altherma_hub_1
  uart_id: uart_bus
  update_interval: 30s

# select:
#   - platform: template
#     name: "Heat pump Model"
#     id: heat_pump_model
#     options:
#       - "ERGA D EHV-EHB-EHVZ DA series"
#     initial_option: "ERGA D EHV-EHB-EHVZ DA series"
#     optimistic: true

packages:
  # Uncomment below if you want to "Take Control" in ESPHome Device Builder
  # altherma_sensors: !include github://jjohnsen/esphome-altherma/confs/erga_eh_da_04_08.yaml@main
  # Comment below if you want to "Take Control" in ESPHome Device Builder
  altherma_sensors: !include confs/erga_eh_da_04_08.yaml