packages:
  base: !include base.yaml

esphome:
  name: esphome-altherma
  friendly_name: ESPHome Altherma
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

api:
  encryption:
   key: !secret ha_api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Altherma Fallback Hotspot"
    password: !secret hotspot_password
captive_portal:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
    encryption:
